name: jhoom
description: A short video App.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  firebase_messaging: ^6.0.16
  google_sign_in: ^4.5.3
  geolocator: ^5.3.2+2
  animator: ^1.0.0+5           # don't update the animator plugin.
  timeago: ^2.0.27
  cached_network_image: ^2.3.1
  image: ^2.1.14
  audioplayers: ^0.16.0
  flick_video_player: ^0.1.1
  camera: ^0.5.8+5
  video_trimmer: ^0.2.7        # video trimmer providing ffmpeg plugin files(flutter_ffmpeg: ^0.2.10)=>to make the app size less if not try to remove video trimmer
  permission_handler: ^5.0.1+1
  file_picker: ^1.13.3
  image_picker: ^0.6.7+7
  dio: ^3.0.10
  file_utils: ^0.1.4
  visibility_detector: ^0.1.5
  fluttertoast: ^7.0.3
  wc_flutter_share: ^0.2.2
  cached_video_player: ^1.0.3
  video_player: ^0.10.12+2
  flutter_downloader: ^1.5.0
  curved_navigation_bar: ^0.3.4
#  in_app_update:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/filters/
    - assets/images/Notification/
    - assets/images/PostPage/
    - assets/images/Profile/
    - assets/images/Search/
    - assets/images/Upload/
    - assets/images/Upload/MusicIcons/
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

    - family: SaucerBB
      fonts:
        - asset: assets/fonts/SaucerBB.ttf